eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-primary:8761/eureka/,http://eureka-secondary:8762/eureka/,http://eureka-tertiary:8763/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
