---
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-primary:8761/eureka/,http://eureka-secondary:8762/eureka/,http://eureka-tertiary:8763/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles:
    activate-on: subject
words: I,You,He,She,It
  
---
spring:
  profiles:
    activate-on: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles:
    activate-on: article
words: a,the

---
spring:
  profiles:
    activate-on: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles:
    activate-on: noun
words: boat,book,vote,seat,backpack,partition,groundhog
